micronaut:
    security:
        enabled: true
    application:
        name: fake news api
    server:
        host: 192.168.1.2
        port: 8080
        cors:
            enabled: true
datasources:
    default:
        url: jdbc:postgresql://localhost:5433/fake_news
        username: back
        password: change.me
        driverClassName: org.postgresql.Driver
        validationQuery: SELECT 1
#        initSQL: SET search_path TO isfront
activemq:
    brokerUrl: tcp://localhost:61616
    login: neoru4
    password: change.me
